topic 8
Arisa04/python pull request #7
Opened 2022-01-25 16:44 UTC by Arisa04

topic_8を提出します。

2022-01-26 04:40 UTC, LinearRain requested changes
Str型以外にBool型も指定できるので、使用してみてください

2022-01-26 04:40 UTC, LinearRain commented on 08/08_D.py
> +ans = str(str2 in str1)
if文は、str型以外にもbool型も使用できるので、ansをstr型ではなくbool型で使いましょう。
`ans = str2 in str1`
`if ans == True`

2022-01-26 16:24 UTC, Arisa04 commented
レビューありがとうございます！
修正してみました。

2022-01-26 16:35 UTC, LinearRain approved these changes
修正を確認しました！対応ありがとうございます。

2022-01-31 13:11 UTC, tani1108 commented
確認しました！
OKです！

2022-02-02 06:45 UTC, merged